baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'Jayanta Kurumathur'
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
profilePicture = "images/pfp.jpg"

enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"